// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1occCkHei_BNpzfzms1-q793pBW10090',
    appId: '1:475574709739:web:76a86bd185563ff4827dae',
    messagingSenderId: '475574709739',
    projectId: 'linkup-9ac02',
    authDomain: 'linkup-9ac02.firebaseapp.com',
    storageBucket: 'linkup-9ac02.firebasestorage.app',
    measurementId: 'G-H5YFMK62CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4dJb-ilcTW_YN43slGh4wRJZbwDHQBSo',
    appId: '1:475574709739:android:f8f8c7f50308980f827dae',
    messagingSenderId: '475574709739',
    projectId: 'linkup-9ac02',
    storageBucket: 'linkup-9ac02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeOAVPUbkANhzQdSwVE_B_9s72hmHN-HA',
    appId: '1:475574709739:ios:e6b9f12f9bcbc886827dae',
    messagingSenderId: '475574709739',
    projectId: 'linkup-9ac02',
    storageBucket: 'linkup-9ac02.firebasestorage.app',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeOAVPUbkANhzQdSwVE_B_9s72hmHN-HA',
    appId: '1:475574709739:ios:e6b9f12f9bcbc886827dae',
    messagingSenderId: '475574709739',
    projectId: 'linkup-9ac02',
    storageBucket: 'linkup-9ac02.firebasestorage.app',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1occCkHei_BNpzfzms1-q793pBW10090',
    appId: '1:475574709739:web:689a367737fa76ee827dae',
    messagingSenderId: '475574709739',
    projectId: 'linkup-9ac02',
    authDomain: 'linkup-9ac02.firebaseapp.com',
    storageBucket: 'linkup-9ac02.firebasestorage.app',
    measurementId: 'G-NY6S7853BV',
  );
}
